### ISSUE TITLE
音乐播放器貌似没法调节音量；希望可以加个倒计时的功能，类似高考倒计时之类的

### ISSUE THREAD

**Issue by Timacoldplay** [fzf404/Monit#24]
而且，这个窗口似乎也没办法调节大小，待办字稍微多一点后面就看不见了

**Comment by fzf404** [comment]
为什么都喜欢把内容写在标题里。。。

**Comment by fzf404** [comment]
> 音乐播放器貌似没法调节音量

暂时没做，继承自系统音量。

> 希望可以加个倒计时的功能，类似高考倒计时之类的

复议。

> 而且，这个窗口似乎也没办法调节大小，待办字稍微多一点后面就看不见了

确实不允许用户调节大小，后期可以考虑增加部分窗口的调节功能。

**Comment by Timacoldplay** [comment]
> 为什么都喜欢把内容写在标题里。。。

这不更直观嘛

**Comment by fzf404** [comment]
谢谢你的建议～

**Comment by Timacoldplay** [comment]
> 谢谢你的建议～
我谢谢你才对哈哈

**Comment by fzf404** [comment]
关于窗口自动调节大小，经过考虑还是不合并至主分支，可以前往 `custom-size` 分支查看。

**Comment by fzf404** [comment]
已将这些功能建议添加至 Discussions 中！
