### ISSUE TITLE
按下Win+D时会最小化

### ISSUE THREAD

**Issue by hejie13250** [fzf404/Monit#27]
如题

**Comment by fzf404** [comment]
我尝试解决一下

**Comment by fzf404** [comment]
所以这是win的特性，将窗口置顶后将解决此问题。

**Comment by fzf404** [comment]
目前想了一个解决方案，可以使用 `Ctrl + Shift + Alt + M` 快捷键激活全部已开启窗口。

**Comment by fzf404** [comment]
下一次版本更新就会加上这个功能。

**Comment by fzf404** [comment]
已完成解决方案。

**Comment by fzf404** [comment]
已完成解决方案。

**Comment by pzhren** [comment]
> 已完成解决方案。

能不能做一个桌面置顶，win+D回到桌面就消失了，置顶又会浮到所有窗口上面，很难受
