### ISSUE TITLE
I made a big sur theme icon for app, can i add it in to this project?

### ISSUE THREAD

**Issue by Erica-Iris** [fzf404/Monit#28]
I made a big sur theme icon for app, it make's my dock more tidy.
looks like this [![png](https://s1.ax1x.com/2022/11/07/xvq5nA.png)](https://imgse.com/i/xvq5nA)

**Comment by fzf404** [comment]
of course!

**Comment by fzf404** [comment]
I haven't had this problem, I'll look at it tomorrow morning, I have a QQ channel： https://pd.qq.com/s/5bzu3lz3c

**Comment by fzf404** [comment]
I didn't have any problems during my build， you can submit PR directly.
