### ISSUE TITLE
音乐插件-增加歌单列表

### ISSUE THREAD

**Issue by snow2zhou** [fzf404/Monit#33]
![图片](https://user-images.githubusercontent.com/44360310/203493232-a85fba21-e71a-465a-bab6-e45ffa596b65.png)
请问音乐插件能否增加一个歌单列表功能，就是可以保存多条【请求地址、歌单ID记录】，然后可以根据需要选择对应的歌单列表，显示播放对应的歌曲内容。
如果歌单列表能再增加一列【自定义名称】字段就更好了，可以自己输入文字并最后在列表中显示，这样可以方便自己进行备注查看。

**Comment by fzf404** [comment]
这个已经在计划列表中了，下一次版本更新就会增加通过歌单名选择歌单的功能

**Comment by snow2zhou** [comment]
> 这个已经在计划列表中了，下一次版本更新就会增加通过歌单名选择歌单的功能

好滴，期待中。。。

**Comment by fzf404** [comment]
已经发布在最新的 release 中了 #36
