### ISSUE TITLE
音乐模块一直在加载中

### ISSUE THREAD

**Issue by GwG0703** [fzf404/Monit#40]
![image](https://user-images.githubusercontent.com/71363861/210764436-3f11c79f-3900-42d3-ace3-639748bdb319.png)

**Comment by fzf404** [comment]
鼠标聚焦到插件，按一下 Ctrl + R，不过在做这个操作之前，可以帮我按一下 Ctrl + Shift + I ，截一下 Console 中的报错信息嘛？

**Comment by fzf404** [comment]
Console 如果很小看不清，可以点击右边的悬浮图标，把控制台独立出来。

**Comment by GwG0703** [comment]
谢谢你的提醒，我是通过重置重新登录已经解决了这个问题，可能是我前不久清除了浏览器的cookies缓存导致的，目前已经能正常运行的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzf404/Monit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月5日(星期四) 晚上7:09
***@***.***&gt;;
抄送:&nbsp;"1035 金管2009 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzf404/Monit] 音乐模块一直在加载中 (Issue #40)





 
鼠标聚焦到插件，按一下 Ctrl + R，不过在做这个操作之前，可以帮我按一下 Ctrl + Shift + I ，截一下 Console 中的报错信息嘛？

**Comment by fzf404** [comment]
好的，不过你的邮件回复逻辑该换了（容易暴露隐私）。

![image](https://user-images.githubusercontent.com/40832831/210767247-39b28222-6e43-4b35-8ac8-82cdb9705e2a.png)
