### ISSUE TITLE
能否设置便捷版？

### ISSUE THREAD

**Issue by realcirno** [fzf404/Monit#42]
能否设置便捷版？这样重装系统之后不需要再配置

**Comment by fzf404** [comment]
配置文件备份已经在计划中了，目前可以参考 [代码位置](https://monit.fzf404.art/#/zh/02-summary?id=%f0%9f%8d%bb-%e4%bb%a3%e7%a0%81%e4%bd%8d%e7%bd%ae) 中的 `7. 配置文件位置` 手动备份 JSON 格式的配置文件。
