### ISSUE TITLE
0.8.0版本开启报错

### ISSUE THREAD

**Issue by woshiqiji** [fzf404/Monit#47]
![Snipaste_2023-04-13_11-07-55](https://user-images.githubusercontent.com/84630421/231640306-261e2935-ea4d-4d38-b0b7-5dbd35591343.png)

**Comment by fzf404** [comment]
配置文件有问题？看一下 `C:\Users\[user]\AppData\Roaming\monit\config.json` 文件的内容。

**Comment by fzf404** [comment]
可能因为之前的版本很低，0.8.0的配置文件结构和0.4.0以前的结构不一样。

**Comment by woshiqiji** [comment]
那我应该怎么解决，其他版本都正常，就这个8版本有问题

听古巴比伦在唱歌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzf404/Monit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzf404/Monit] 0.8.0版本开启报错 (Issue #47)





 
可能因为之前的版本很低，0.8.0的配置文件结构和0.4.0以前的结构不一样。

**Comment by fzf404** [comment]
把我前面说的那个文件删掉重新打开就可以了

**Comment by fzf404** [comment]
在删除之前可以给我看看里面的内容吗，我正好看看哪里有问题

**Comment by woshiqiji** [comment]
> 在删除之前可以给我看看里面的内容吗，我正好看看哪里有问题

{
	"__internal__": {
		"migrations": {
			"version": "0.8.0"
		}
	},
	"welcome": {
		"x": 728,
		"y": 414
	},
	"clock": {
		"x": 1473,
		"y": 838
	}
}

**Comment by woshiqiji** [comment]
> 在删除之前可以给我看看里面的内容吗，我正好看看哪里有问题

`{
	"__internal__": {
		"migrations": {
			"version": "0.8.0"
		}
	},
	"welcome": {
		"x": 728,
		"y": 414
	},
	"clock": {
		"x": 1473,
		"y": 838
	}
}`

**Comment by fzf404** [comment]
看起来没什么问题，删掉后可以用了吗？

**Comment by woshiqiji** [comment]
> 看起来没什么问题，删掉后可以用了吗？

可以了，多谢

**Comment by woshiqiji** [comment]
> > 看起来没什么问题，删掉后可以用了吗？
> 
> 可以了，多谢

可以考虑做一下鼠标穿透效果吗？

**Comment by fzf404** [comment]
可以！

**Comment by fzf404** [comment]
已在最新版本中解决此问题。
