### ISSUE TITLE
pnpm release 发布到github报错

### ISSUE THREAD

**Issue by lcyh** [fzf404/Monit#49]
<img width="1683" alt="image" src="https://user-images.githubusercontent.com/26177202/235347188-245004a9-66d6-4302-9ca0-f4c9c76420c2.png">

直接将代码拉下来，新建了一个githuab仓库，然后添加 GH_TOKEN，运行pnpm release 报错了

**Comment by fzf404** [comment]
啊这，报错信息不是说的很清楚嘛，`GH_TOKEN`不能明文写进配置里。

**Comment by lcyh** [comment]
已收到，谢谢

**Comment by lcyh** [comment]
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/26177202/235437647-40757cfa-af30-4602-90a4-056f8d34637a.png">
github仓库设置GH_TOKEN环境变量也报错，发布到github是不是还需要配置什么？

**Comment by lcyh** [comment]
/*
 * @Author: changluo
 * @Description:
 * @LastEditors: luc19964 luochang@gopherasset.com
 */
const path = require('path')

const resolve = (dir) => {
  return path.join(__dirname, dir)
}

const config = {
  configureWebpack: {
    // electron 入口
    entry: './core/main.js'
  },
  chainWebpack: (config) => {
    // import 别名
    config.resolve.alias.set('~', resolve('./')).set('@', resolve('app'))
    // svg 加载
    config.module.rule('svg').delete('type').use('svg-vue3-loader').loader('svg-vue3-loader')
  },
  pluginOptions: {
    // electron 打包配置
    electronBuilder: {
      // 输出路径
      outputDir: 'release',
      // node 集成
      nodeIntegration: true,
      // 自定义通信协议
      customFileProtocol: 'monit://./',
      // 主进程入口
      mainProcessFile: 'core/main.ts',
      // 渲染进程入口
      rendererProcessFile: 'app/main.ts',
      chainWebpackMainProcess: (config) => {
        config.resolve.alias.set('~', resolve('./'))
      },
      // 构建选项
      builderOptions: {
        // 应用名
        productName: 'lc-Monit',
        // 图标
        icon: 'public/img/icon.png',
        // 应用 ID
        appId: 'lcyhy.com',
        // 打包命名
        artifactName: '${productName}-${version}-${os}-${arch}.${ext}',
        // 发布地址
        publish: ['github'],
        // 多平台配置
        win: {
          target: ['nsis', '7z']
        },
        linux: {
          target: 'AppImage'
        },
        mac: {
          target: {
            target: 'dmg',
            arch: ['x64', 'arm64']
          },
          entitlements: 'entitlements.mac.plist',
          extendInfo: {
            NSMicrophoneUsageDescription: '请提供您的麦克风权限！',
            NSCameraUsageDescription: '请提供您的相机权限！'
          }
        }
      }
    }
  }
}

if (process.env.NODE_ENV === 'development') {
  // 热重载配置
  config.pluginOptions.electronBuilder.mainProcessWatch = ['config/*.ts', 'core/*.ts', 'event/*.ts', 'server/*.ts']
}

module.exports = { ...config }
这是vue.config.js 配置文件，跟你的配置文件差不多

**Comment by lcyh** [comment]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/26177202/235437995-48fbe1f2-b4d0-41c5-8334-b16528eeeb7c.png">
这是vue.config.js配置，跟你的配置差不多的

**Comment by fzf404** [comment]
你是用命令行的方式推送的吗？我这个配置是使用 github action 进行发布的 你看一下 release 里应该有 darft 了。

**Comment by fzf404** [comment]
前提是你推了个 tag 上去，action 应该会自动运行

**Comment by fzf404** [comment]
要是想在本地推送 release ，需要自行配置 gh_token 环境变量。而且只能推送当前平台的打包结果，electron builder 没有交叉编译的功能。

**Comment by fzf404** [comment]
刚才应该还是没说清楚，打包发布有两个渠道。
第一个方式：使用 pnpm publish ，这个方式需要生成 personal token，然后配置在终端环境变量里。之后就可以推送了。
第二个方式：通过 github action 打包，需要在自己的仓库里新增 secret 密钥，推送完代码还需要打一个 tag ，然后推上去，之后 release 的草稿里就有了，我那个 action 文件里是检测到版本发布才进行打包操作。

**Comment by lcyh** [comment]
已收到，谢谢
