### ISSUE TITLE
窗口置顶概率失效，且概率有点大

### ISSUE THREAD

**Issue by Timacoldplay** [fzf404/Monit#51]

**Comment by Timacoldplay** [comment]
窗口置顶概率失效，且概率有点大

**Comment by fzf404** [comment]
emmm，我没遇到过这种问题，可以详细描述一下吗？

**Comment by Timacoldplay** [comment]
> emmm，我没遇到过这种问题，可以详细描述一下吗？

我试了下办公室电脑没问题，但是我自己电脑就置顶就有问题，我一直在副屏上放着呢，应该跟这没关系吧

**Comment by Timacoldplay** [comment]
> emmm，我没遇到过这种问题，可以详细描述一下吗？

图像这部分比较难用，图片没法放大缩小，窗口太小了看也看不清，也没法顺时针或者逆时针旋转，要是能直接往窗口里面拖照片就好了

**Comment by fzf404** [comment]
已将这些功能建议添加至 Discussions 中！
