### ISSUE TITLE
music无法播放

### ISSUE THREAD

**Issue by lcyh** [fzf404/Monit#54]
<img width="1096" alt="image" src="https://github.com/fzf404/Monit/assets/26177202/e4c4394c-eaad-40df-8dc6-5f1ad1e51bc9">
音乐播放器里的音乐不能播放了吗

**Comment by fzf404** [comment]
我这边测试正常

**Comment by lcyh** [comment]
已收到，谢谢

**Comment by fzf404** [comment]
暂无更多信息，所以暂时关闭此问题。
